[package]
name = "asvc_rollup"
version = "0.1.0"
authors = ["even <even@secbit.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
