[package]
name = "asvc_unlock"
version = "0.1.0"
authors = ["SECBIT Labs"]
edition = "2018"

[dependencies]
ckb-std = "0.6.0"

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
